# Generated by Django 5.2 on 2026-04-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('readiness_score', models.PositiveSmallIntegerField()),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('recovery_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_scores',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('hrv', 'HRV'), ('resting_hr', 'Resting Heart Rate'), ('steps', 'Steps'), ('sleep_duration', 'Sleep Duration'), ('sleep_quality', 'Sleep Quality'), ('calories', 'Calories Burned'), ('spo2', 'Blood Oxygen Saturation'), ('stress', 'Stress Score')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.connecteddevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'metric_type', 'recorded_at'], name='health_metr_user_id_0c3a65_idx')],
            },
        ),
    ]
