[mypy]
plugins = mypy_django_plugin.main
django_settings_module = bioiq.settings.local
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = "bioiq.settings.local"

[mypy-*.migrations.*]
ignore_errors = True
