# Generated by Django 5.2 on 2026-04-30 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('provider_email', models.EmailField(max_length=254)),
                ('provider_type', models.CharField(choices=[('physician', 'Physician'), ('coach', 'Health Coach'), ('specialist', 'Specialist'), ('other', 'Other')], default='other', max_length=20)),
                ('access_level', models.CharField(choices=[('read_summary', 'Read Summary'), ('read_full', 'Read Full'), ('read_metrics', 'Read Metrics')], default='read_summary', max_length=20)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'provider_accesses',
            },
        ),
    ]
